# Generated by Django 5.1.6 on 2025-02-14 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_userprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exemplaryspeech',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
