# Generated by Django 5.1.6 on 2025-02-14 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_exemplaryspeech_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='exemplaryspeech',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='exemplaryspeech',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('embedding', 'Generating Embedding'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
