# Generated by Django 5.1.6 on 2025-02-15 05:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_exemplaryspeech_error_message_exemplaryspeech_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userspeech',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='userspeech',
            name='feedback',
        ),
        migrations.RemoveField(
            model_name='userspeech',
            name='filler_word_count',
        ),
        migrations.AddField(
            model_name='userspeech',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='date_delivered',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='filler_words',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='improvement_areas',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='is_live',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='live_session_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='live_transcript',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='occasion',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='pause_duration',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('transcribing', 'Transcribing'), ('embedding', 'Generating Embedding'), ('analyzing', 'Analyzing Speech'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='strengths',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='userspeech',
            name='volume_variation',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userspeech',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='userspeech',
            name='transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
