# Generated by Django 5.1.6 on 2025-02-15 21:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_userspeech_duration_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_role', models.CharField(max_length=255)),
                ('interview_type', models.CharField(choices=[('behavioral', 'Behavioral'), ('technical', 'Technical'), ('case_study', 'Case Study')], max_length=20)),
                ('duration_minutes', models.IntegerField(choices=[(5, '5 minutes'), (15, '15 minutes'), (30, '30 minutes')], default=15)),
                ('resume_url', models.URLField(blank=True, null=True)),
                ('linkedin_url', models.URLField(blank=True, null=True)),
                ('current_question', models.TextField(blank=True, null=True)),
                ('questions_asked', models.JSONField(default=list)),
                ('answers_given', models.JSONField(default=list)),
                ('clarity_score', models.FloatField(null=True)),
                ('structure_score', models.FloatField(null=True)),
                ('relevance_score', models.FloatField(null=True)),
                ('confidence_score', models.FloatField(null=True)),
                ('ai_feedback', models.JSONField(null=True)),
                ('suggested_improvements', models.JSONField(null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(null=True)),
                ('completed_at', models.DateTimeField(null=True)),
                ('next_session_scheduled', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
